# Generated by Django 5.2.5 on 2025-08-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoanalizado',
            name='texto_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textoanalizado',
            name='texto_procesado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
