# Generated by Django 5.2.5 on 2025-09-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_textoanalizado_texto_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('ngrama', models.CharField(max_length=255)),
                ('conteo', models.IntegerField(default=1)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngramas', to='analisis.textoanalizado')),
            ],
        ),
    ]
