# Generated by Django 5.2.5 on 2025-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_ngrama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngrama',
            name='conteo',
        ),
        migrations.RemoveField(
            model_name='ngrama',
            name='ngrama',
        ),
        migrations.AddField(
            model_name='ngrama',
            name='frecuencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngrama',
            name='secuencia',
            field=models.TextField(default=''),
        ),
    ]
