# Generated by Django 5.2.5 on 2025-09-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_remove_ngrama_conteo_remove_ngrama_ngrama_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngrama',
            options={'ordering': ['-frecuencia', 'secuencia']},
        ),
    ]
